# Generated by Django 2.1.7 on 2019-03-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steganography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.ImageField(default='', upload_to='gallery')),
                ('payload', models.ImageField(default='', upload_to='gallery')),
                ('retImg', models.ImageField(default='', upload_to='gallery')),
            ],
        ),
    ]
